package setup

// skeletonMetrics is the base metrics.toml written on every node.
// All sections enabled, empty filter lists mean "report everything".
// processes.limit matches defaultProcessLimit in internal/config/metrics.go (20).
const skeletonMetrics = `# /etc/tailkitd/integrations/metrics.toml
# Generated by: tailkitd install
#
# All sections are independent — disable any without affecting the others.
# Restart tailkitd after editing this file.

[host]
enabled = true

[cpu]
enabled = true

[memory]
enabled = true

[disk]
enabled = true
# Restrict to specific mount points, or leave empty to report all filesystems.
paths = []

[network]
enabled = true
# Restrict to specific interfaces by name, or leave empty to report all.
interfaces = []

[processes]
enabled = true
# Processes returned, sorted by CPU usage desc. Range: 1–100.
limit = 20
`

// skeletonFiles is the base files.toml written on every node.
// Two rules: a safe write-only drop zone, and read access to the
// config directory for tools that inspect integration state.
// Both rules pass validateFilesConfig without modification.
const skeletonFiles = `# /etc/tailkitd/integrations/files.toml
# Generated by: tailkitd install
#
# Each [[path]] entry grants access to one directory.
#   dir       — absolute path, must end with /
#   allow     — one or both of: "read", "write"
#   use_as    — username to switch to when writing (optional, default: tailkitd)
#
# Restart tailkitd after editing this file.

# Dedicated drop zone for files pushed over the tailnet.
# Isolated from the rest of the node. Safe default write target for any tool.
[[path]]
dir   = "/var/lib/tailkitd/recv/"
allow = ["write"]

# Read access to the tailkitd config directory.
# Lets tools inspect which integrations are configured without modifying them.
# Never add "write" here — config changes require a tailkitd restart.
[[path]]
dir   = "/etc/tailkitd/"
allow = ["read"]
`

// skeletonVars is the base vars.toml written on every node.
// One placeholder scope so the file passes validateVarsConfig
// (at least one [[scope]] is required). The operator replaces
// "myapp" and "prod" with their actual project and environment.
const skeletonVars = `# /etc/tailkitd/integrations/vars.toml
# Generated by: tailkitd install
#
# Each [[scope]] entry grants access to one project/env combination.
#   project — identifier, must match ^[a-z0-9_-]+$
#   env     — identifier, must match ^[a-z0-9_-]+$
#   allow   — one or both of: "read", "write"
#
# Keys starting with _ are reserved and cannot be set by callers.
# Restart tailkitd after editing this file.

# Replace "myapp" and "prod" with your actual project name and environment.
[[scope]]
project = "myapp"
env     = "prod"
allow   = ["read", "write"]
`

// skeletonDocker is the base docker.toml written when Docker is present.
// Conservative defaults:
//   - containers: all safe ops; "remove" excluded (destructive, hard to undo)
//   - images: list only; "pull" excluded (supply-chain risk)
//   - compose: lifecycle ops; "build" excluded (arbitrary context execution)
//   - swarm: disabled entirely; "write" excluded (affects entire cluster)
const skeletonDocker = `# /etc/tailkitd/integrations/docker.toml
# Generated by: tailkitd install
# Only written when /var/run/docker.sock is present at install time.
#
# Per-section: set enabled = false to block the entire section (returns 403).
# allow lists the permitted operations within each enabled section.
# Restart tailkitd after editing this file.

[containers]
enabled = true
# Valid: list, inspect, logs, stats, start, stop, restart, remove
# "remove" is excluded from the default — destructive and not easily undone.
allow = ["list", "inspect", "logs", "stats", "start", "stop", "restart"]

[images]
enabled = true
# Valid: list, pull
# "pull" is excluded from the default — adds supply-chain risk.
allow = ["list"]

[compose]
enabled = true
# Valid: list, up, down, pull, restart, build
# "build" is excluded from the default — executes arbitrary build context.
allow = ["list", "up", "down", "restart"]

[swarm]
# Disabled by default. Swarm write ops affect the entire cluster immediately.
# Set enabled = true and add "read" (and optionally "write") only when needed.
enabled = false
# Valid: read, write
allow = ["read"]
`

// skeletonSystemd is the base systemd.toml written when systemd is PID 1.
// Conservative defaults:
//   - units: read + lifecycle ops; "enable"/"disable" excluded (persist across reboots)
//   - journal: per-unit only; system_journal = false (system journal may expose secrets)
const skeletonSystemd = `# /etc/tailkitd/integrations/systemd.toml
# Generated by: tailkitd install
# Only written when systemd is PID 1 at install time.
#
# Restart tailkitd after editing this file.

[units]
enabled = true
# Valid: list, inspect, unit_file, logs, start, stop, restart, reload, enable, disable
# "enable" and "disable" are excluded from the default — they persist across reboots.
allow = ["list", "inspect", "unit_file", "logs", "start", "stop", "restart", "reload"]

[journal]
enabled = true
# Minimum log severity to return.
# Valid: emerg, alert, crit, err, warning, notice, info, debug
priority = "info"
# Default number of journal lines returned per request. Must be > 0.
lines = 100
# Permit GET /integrations/systemd/journal (system-wide journal).
# false restricts to per-unit journal only — system journal may expose secrets
# from unrelated services. Enable only when you need it.
system_journal = false
`
